import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-unemployment-insurance-rate-audit",
  "engine": "recovery",
  "title": "Unemployment Insurance Contribution Rate Audit",
  "shortTitle": "Unemployment Insurance Contribution Rate Audit",
  "tagline": "Reduce unemployment tax through benefit-charge review, experience transfers, voluntary contributions, and timely rate protests.",
  "industry": "Employment Tax Recovery",
  "buyer": "Multi-state employers and payroll teams",
  "uiPort": 4694,
  "apiPort": 5694,
  "accent": "#7e22ce",
  "currency": "USD",
  "primaryOutcome": "Unemployment Insurance Contribution Rate Audit converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect state accounts, payroll, taxable wage bases, experience ratings, benefit charges, acquisitions, layoffs, voluntary contributions, rate notices, protests, and refunds in one accountable workflow. Reduce unemployment tax through benefit-charge review, experience transfers, voluntary contributions, and timely rate protests.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Unemployment Insurance Contribution Rate Audit evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("state-account-registry","UIR01","State account registry","Execute state account registry using state accounts, payroll, taxable wage bases, experience ratings, benefit charges, acquisitions, layoffs, voluntary contributions, rate notices, protests, and refunds.","Produce a governed state account registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / State Account","text","Employer / State Account · Standard Case"],["caseReference","State account registry Reference","text","UIR01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1208750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1462588],["domainDriver","Rate Driver","select","Benefit charge",["Benefit charge","Successor transfer","Voluntary contribution"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["State account registry case","Taxable wage ingestion case","Rate notice extraction case","Benefit charge statement case","Former employee matching case"]}),
feature("taxable-wage-ingestion","UIR02","Taxable wage ingestion","Execute taxable wage ingestion using state accounts, payroll, taxable wage bases, experience ratings, benefit charges, acquisitions, layoffs, voluntary contributions, rate notices, protests, and refunds.","Produce a governed taxable wage ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / State Account","text","Employer / State Account · Standard Case"],["caseReference","Taxable wage ingestion Reference","text","UIR02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1208750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1462588],["domainDriver","Rate Driver","select","Benefit charge",["Benefit charge","Successor transfer","Voluntary contribution"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["State account registry case","Taxable wage ingestion case","Rate notice extraction case","Benefit charge statement case","Former employee matching case"]}),
feature("rate-notice-extraction","UIR03","Rate notice extraction","Execute rate notice extraction using state accounts, payroll, taxable wage bases, experience ratings, benefit charges, acquisitions, layoffs, voluntary contributions, rate notices, protests, and refunds.","Produce a governed rate notice extraction decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / State Account","text","Employer / State Account · Standard Case"],["caseReference","Rate notice extraction Reference","text","UIR03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1208750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1462588],["domainDriver","Rate Driver","select","Benefit charge",["Benefit charge","Successor transfer","Voluntary contribution"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["State account registry case","Taxable wage ingestion case","Rate notice extraction case","Benefit charge statement case","Former employee matching case"]}),
feature("benefit-charge-statement","UIR04","Benefit charge statement","Execute benefit charge statement using state accounts, payroll, taxable wage bases, experience ratings, benefit charges, acquisitions, layoffs, voluntary contributions, rate notices, protests, and refunds.","Produce a governed benefit charge statement decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / State Account","text","Employer / State Account · Standard Case"],["caseReference","Benefit charge statement Reference","text","UIR04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1208750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1462588],["domainDriver","Rate Driver","select","Benefit charge",["Benefit charge","Successor transfer","Voluntary contribution"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["State account registry case","Taxable wage ingestion case","Rate notice extraction case","Benefit charge statement case","Former employee matching case"]}),
feature("former-employee-matching","UIR05","Former employee matching","Execute former employee matching using state accounts, payroll, taxable wage bases, experience ratings, benefit charges, acquisitions, layoffs, voluntary contributions, rate notices, protests, and refunds.","Produce a governed former employee matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / State Account","text","Employer / State Account · Standard Case"],["caseReference","Former employee matching Reference","text","UIR05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1208750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1462588],["domainDriver","Rate Driver","select","Benefit charge",["Benefit charge","Successor transfer","Voluntary contribution"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["State account registry case","Taxable wage ingestion case","Rate notice extraction case","Benefit charge statement case","Former employee matching case"]}),
feature("ineligible-charge-detection","UIR06","Ineligible charge detection","Execute ineligible charge detection using state accounts, payroll, taxable wage bases, experience ratings, benefit charges, acquisitions, layoffs, voluntary contributions, rate notices, protests, and refunds.","Produce a governed ineligible charge detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / State Account","text","Employer / State Account · Standard Case"],["caseReference","Ineligible charge detection Reference","text","UIR06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1208750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1462588],["domainDriver","Rate Driver","select","Benefit charge",["Benefit charge","Successor transfer","Voluntary contribution"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["State account registry case","Taxable wage ingestion case","Rate notice extraction case","Benefit charge statement case","Former employee matching case"]}),
feature("experience-rating-calculation","UIR07","Experience rating calculation","Execute experience rating calculation using state accounts, payroll, taxable wage bases, experience ratings, benefit charges, acquisitions, layoffs, voluntary contributions, rate notices, protests, and refunds.","Produce a governed experience rating calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / State Account","text","Employer / State Account · Standard Case"],["caseReference","Experience rating calculation Reference","text","UIR07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1208750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1462588],["domainDriver","Rate Driver","select","Benefit charge",["Benefit charge","Successor transfer","Voluntary contribution"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["State account registry case","Taxable wage ingestion case","Rate notice extraction case","Benefit charge statement case","Former employee matching case"]}),
feature("successor-predecessor-transfer","UIR08","Successor predecessor transfer","Execute successor predecessor transfer using state accounts, payroll, taxable wage bases, experience ratings, benefit charges, acquisitions, layoffs, voluntary contributions, rate notices, protests, and refunds.","Produce a governed successor predecessor transfer decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / State Account","text","Employer / State Account · Standard Case"],["caseReference","Successor predecessor transfer Reference","text","UIR08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1208750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1462588],["domainDriver","Rate Driver","select","Benefit charge",["Benefit charge","Successor transfer","Voluntary contribution"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["State account registry case","Taxable wage ingestion case","Rate notice extraction case","Benefit charge statement case","Former employee matching case"]}),
feature("joint-account-analysis","UIR09","Joint account analysis","Execute joint account analysis using state accounts, payroll, taxable wage bases, experience ratings, benefit charges, acquisitions, layoffs, voluntary contributions, rate notices, protests, and refunds.","Produce a governed joint account analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / State Account","text","Employer / State Account · Standard Case"],["caseReference","Joint account analysis Reference","text","UIR09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1208750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1462588],["domainDriver","Rate Driver","select","Benefit charge",["Benefit charge","Successor transfer","Voluntary contribution"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["State account registry case","Taxable wage ingestion case","Rate notice extraction case","Benefit charge statement case","Former employee matching case"]}),
feature("voluntary-contribution-model","UIR10","Voluntary contribution model","Execute voluntary contribution model using state accounts, payroll, taxable wage bases, experience ratings, benefit charges, acquisitions, layoffs, voluntary contributions, rate notices, protests, and refunds.","Produce a governed voluntary contribution model decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / State Account","text","Employer / State Account · Standard Case"],["caseReference","Voluntary contribution model Reference","text","UIR10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1208750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1462588],["domainDriver","Rate Driver","select","Benefit charge",["Benefit charge","Successor transfer","Voluntary contribution"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["State account registry case","Taxable wage ingestion case","Rate notice extraction case","Benefit charge statement case","Former employee matching case"]}),
feature("rate-protest-deadline","UIR11","Rate protest deadline","Execute rate protest deadline using state accounts, payroll, taxable wage bases, experience ratings, benefit charges, acquisitions, layoffs, voluntary contributions, rate notices, protests, and refunds.","Produce a governed rate protest deadline decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / State Account","text","Employer / State Account · Standard Case"],["caseReference","Rate protest deadline Reference","text","UIR11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1208750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1462588],["domainDriver","Rate Driver","select","Benefit charge",["Benefit charge","Successor transfer","Voluntary contribution"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["State account registry case","Taxable wage ingestion case","Rate notice extraction case","Benefit charge statement case","Former employee matching case"]}),
feature("protest-evidence-package","UIR12","Protest evidence package","Execute protest evidence package using state accounts, payroll, taxable wage bases, experience ratings, benefit charges, acquisitions, layoffs, voluntary contributions, rate notices, protests, and refunds.","Produce a governed protest evidence package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / State Account","text","Employer / State Account · Standard Case"],["caseReference","Protest evidence package Reference","text","UIR12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1208750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1462588],["domainDriver","Rate Driver","select","Benefit charge",["Benefit charge","Successor transfer","Voluntary contribution"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["State account registry case","Taxable wage ingestion case","Rate notice extraction case","Benefit charge statement case","Former employee matching case"]}),
feature("amended-return-workflow","UIR13","Amended return workflow","Execute amended return workflow using state accounts, payroll, taxable wage bases, experience ratings, benefit charges, acquisitions, layoffs, voluntary contributions, rate notices, protests, and refunds.","Produce a governed amended return workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / State Account","text","Employer / State Account · Standard Case"],["caseReference","Amended return workflow Reference","text","UIR13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1208750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1462588],["domainDriver","Rate Driver","select","Benefit charge",["Benefit charge","Successor transfer","Voluntary contribution"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["State account registry case","Taxable wage ingestion case","Rate notice extraction case","Benefit charge statement case","Former employee matching case"]}),
feature("refund-reconciliation","UIR14","Refund reconciliation","Execute refund reconciliation using state accounts, payroll, taxable wage bases, experience ratings, benefit charges, acquisitions, layoffs, voluntary contributions, rate notices, protests, and refunds.","Produce a governed refund reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / State Account","text","Employer / State Account · Standard Case"],["caseReference","Refund reconciliation Reference","text","UIR14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1208750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1462588],["domainDriver","Rate Driver","select","Benefit charge",["Benefit charge","Successor transfer","Voluntary contribution"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["State account registry case","Taxable wage ingestion case","Rate notice extraction case","Benefit charge statement case","Former employee matching case"]}),
feature("state-employer-analytics","UIR15","State employer analytics","Execute state employer analytics using state accounts, payroll, taxable wage bases, experience ratings, benefit charges, acquisitions, layoffs, voluntary contributions, rate notices, protests, and refunds.","Produce a governed state employer analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / State Account","text","Employer / State Account · Standard Case"],["caseReference","State employer analytics Reference","text","UIR15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1208750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1462588],["domainDriver","Rate Driver","select","Benefit charge",["Benefit charge","Successor transfer","Voluntary contribution"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["State account registry case","Taxable wage ingestion case","Rate notice extraction case","Benefit charge statement case","Former employee matching case"]})
]);
